/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as AuthedChatIndexRouteImport } from './routes/_authed/chat.index'
import { Route as ApiWebhookGithubRouteImport } from './routes/api/webhook/github'
import { Route as ApiShapesSessionsRouteImport } from './routes/api/shapes/sessions'
import { Route as ApiShapesSessionEventsRouteImport } from './routes/api/shapes/session-events'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentSessionsRouteImport } from './routes/api/agent/sessions'
import { Route as ApiAgentSessionReasoningRouteImport } from './routes/api/agent/session-reasoning'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent/run'
import { Route as ApiAgentKeysRouteImport } from './routes/api/agent/keys'
import { Route as ApiAgentContinueRouteImport } from './routes/api/agent/continue'
import { Route as ApiAgentCancelRouteImport } from './routes/api/agent/cancel'
import { Route as ApiAgentAnswerRouteImport } from './routes/api/agent/answer'
import { Route as AuthedChatSessionIdRouteImport } from './routes/_authed/chat.$sessionId'
import { Route as ApiAgentSessionsIdRouteImport } from './routes/api/agent/sessions.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatIndexRoute = AuthedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedChatRoute,
} as any)
const ApiWebhookGithubRoute = ApiWebhookGithubRouteImport.update({
  id: '/api/webhook/github',
  path: '/api/webhook/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesSessionsRoute = ApiShapesSessionsRouteImport.update({
  id: '/api/shapes/sessions',
  path: '/api/shapes/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesSessionEventsRoute = ApiShapesSessionEventsRouteImport.update({
  id: '/api/shapes/session-events',
  path: '/api/shapes/session-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionsRoute = ApiAgentSessionsRouteImport.update({
  id: '/api/agent/sessions',
  path: '/api/agent/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionReasoningRoute =
  ApiAgentSessionReasoningRouteImport.update({
    id: '/api/agent/session-reasoning',
    path: '/api/agent/session-reasoning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent/run',
  path: '/api/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentKeysRoute = ApiAgentKeysRouteImport.update({
  id: '/api/agent/keys',
  path: '/api/agent/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentContinueRoute = ApiAgentContinueRouteImport.update({
  id: '/api/agent/continue',
  path: '/api/agent/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentCancelRoute = ApiAgentCancelRouteImport.update({
  id: '/api/agent/cancel',
  path: '/api/agent/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAnswerRoute = ApiAgentAnswerRouteImport.update({
  id: '/api/agent/answer',
  path: '/api/agent/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChatSessionIdRoute = AuthedChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AuthedChatRoute,
} as any)
const ApiAgentSessionsIdRoute = ApiAgentSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/chat': typeof AuthedChatRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/chat/$sessionId': typeof AuthedChatSessionIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/cancel': typeof ApiAgentCancelRoute
  '/api/agent/continue': typeof ApiAgentContinueRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/session-reasoning': typeof ApiAgentSessionReasoningRoute
  '/api/agent/sessions': typeof ApiAgentSessionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/shapes/session-events': typeof ApiShapesSessionEventsRoute
  '/api/shapes/sessions': typeof ApiShapesSessionsRoute
  '/api/webhook/github': typeof ApiWebhookGithubRoute
  '/chat/': typeof AuthedChatIndexRoute
  '/api/agent/sessions/$id': typeof ApiAgentSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/chat/$sessionId': typeof AuthedChatSessionIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/cancel': typeof ApiAgentCancelRoute
  '/api/agent/continue': typeof ApiAgentContinueRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/session-reasoning': typeof ApiAgentSessionReasoningRoute
  '/api/agent/sessions': typeof ApiAgentSessionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/shapes/session-events': typeof ApiShapesSessionEventsRoute
  '/api/shapes/sessions': typeof ApiShapesSessionsRoute
  '/api/webhook/github': typeof ApiWebhookGithubRoute
  '/chat': typeof AuthedChatIndexRoute
  '/api/agent/sessions/$id': typeof ApiAgentSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/chat': typeof AuthedChatRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/chat/$sessionId': typeof AuthedChatSessionIdRoute
  '/api/agent/answer': typeof ApiAgentAnswerRoute
  '/api/agent/cancel': typeof ApiAgentCancelRoute
  '/api/agent/continue': typeof ApiAgentContinueRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/run': typeof ApiAgentRunRoute
  '/api/agent/session-reasoning': typeof ApiAgentSessionReasoningRoute
  '/api/agent/sessions': typeof ApiAgentSessionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/shapes/session-events': typeof ApiShapesSessionEventsRoute
  '/api/shapes/sessions': typeof ApiShapesSessionsRoute
  '/api/webhook/github': typeof ApiWebhookGithubRoute
  '/_authed/chat/': typeof AuthedChatIndexRoute
  '/api/agent/sessions/$id': typeof ApiAgentSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/chat'
    | '/dashboard'
    | '/chat/$sessionId'
    | '/api/agent/answer'
    | '/api/agent/cancel'
    | '/api/agent/continue'
    | '/api/agent/keys'
    | '/api/agent/run'
    | '/api/agent/session-reasoning'
    | '/api/agent/sessions'
    | '/api/auth/$'
    | '/api/github/repos'
    | '/api/shapes/session-events'
    | '/api/shapes/sessions'
    | '/api/webhook/github'
    | '/chat/'
    | '/api/agent/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/dashboard'
    | '/chat/$sessionId'
    | '/api/agent/answer'
    | '/api/agent/cancel'
    | '/api/agent/continue'
    | '/api/agent/keys'
    | '/api/agent/run'
    | '/api/agent/session-reasoning'
    | '/api/agent/sessions'
    | '/api/auth/$'
    | '/api/github/repos'
    | '/api/shapes/session-events'
    | '/api/shapes/sessions'
    | '/api/webhook/github'
    | '/chat'
    | '/api/agent/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/_authed/chat'
    | '/_authed/dashboard'
    | '/_authed/chat/$sessionId'
    | '/api/agent/answer'
    | '/api/agent/cancel'
    | '/api/agent/continue'
    | '/api/agent/keys'
    | '/api/agent/run'
    | '/api/agent/session-reasoning'
    | '/api/agent/sessions'
    | '/api/auth/$'
    | '/api/github/repos'
    | '/api/shapes/session-events'
    | '/api/shapes/sessions'
    | '/api/webhook/github'
    | '/_authed/chat/'
    | '/api/agent/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAgentAnswerRoute: typeof ApiAgentAnswerRoute
  ApiAgentCancelRoute: typeof ApiAgentCancelRoute
  ApiAgentContinueRoute: typeof ApiAgentContinueRoute
  ApiAgentKeysRoute: typeof ApiAgentKeysRoute
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiAgentSessionReasoningRoute: typeof ApiAgentSessionReasoningRoute
  ApiAgentSessionsRoute: typeof ApiAgentSessionsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiShapesSessionEventsRoute: typeof ApiShapesSessionEventsRoute
  ApiShapesSessionsRoute: typeof ApiShapesSessionsRoute
  ApiWebhookGithubRoute: typeof ApiWebhookGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat/': {
      id: '/_authed/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedChatIndexRouteImport
      parentRoute: typeof AuthedChatRoute
    }
    '/api/webhook/github': {
      id: '/api/webhook/github'
      path: '/api/webhook/github'
      fullPath: '/api/webhook/github'
      preLoaderRoute: typeof ApiWebhookGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/sessions': {
      id: '/api/shapes/sessions'
      path: '/api/shapes/sessions'
      fullPath: '/api/shapes/sessions'
      preLoaderRoute: typeof ApiShapesSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/session-events': {
      id: '/api/shapes/session-events'
      path: '/api/shapes/session-events'
      fullPath: '/api/shapes/session-events'
      preLoaderRoute: typeof ApiShapesSessionEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/sessions': {
      id: '/api/agent/sessions'
      path: '/api/agent/sessions'
      fullPath: '/api/agent/sessions'
      preLoaderRoute: typeof ApiAgentSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/session-reasoning': {
      id: '/api/agent/session-reasoning'
      path: '/api/agent/session-reasoning'
      fullPath: '/api/agent/session-reasoning'
      preLoaderRoute: typeof ApiAgentSessionReasoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/run': {
      id: '/api/agent/run'
      path: '/api/agent/run'
      fullPath: '/api/agent/run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/keys': {
      id: '/api/agent/keys'
      path: '/api/agent/keys'
      fullPath: '/api/agent/keys'
      preLoaderRoute: typeof ApiAgentKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/continue': {
      id: '/api/agent/continue'
      path: '/api/agent/continue'
      fullPath: '/api/agent/continue'
      preLoaderRoute: typeof ApiAgentContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/cancel': {
      id: '/api/agent/cancel'
      path: '/api/agent/cancel'
      fullPath: '/api/agent/cancel'
      preLoaderRoute: typeof ApiAgentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/answer': {
      id: '/api/agent/answer'
      path: '/api/agent/answer'
      fullPath: '/api/agent/answer'
      preLoaderRoute: typeof ApiAgentAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/chat/$sessionId': {
      id: '/_authed/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AuthedChatSessionIdRouteImport
      parentRoute: typeof AuthedChatRoute
    }
    '/api/agent/sessions/$id': {
      id: '/api/agent/sessions/$id'
      path: '/$id'
      fullPath: '/api/agent/sessions/$id'
      preLoaderRoute: typeof ApiAgentSessionsIdRouteImport
      parentRoute: typeof ApiAgentSessionsRoute
    }
  }
}

interface AuthedChatRouteChildren {
  AuthedChatSessionIdRoute: typeof AuthedChatSessionIdRoute
  AuthedChatIndexRoute: typeof AuthedChatIndexRoute
}

const AuthedChatRouteChildren: AuthedChatRouteChildren = {
  AuthedChatSessionIdRoute: AuthedChatSessionIdRoute,
  AuthedChatIndexRoute: AuthedChatIndexRoute,
}

const AuthedChatRouteWithChildren = AuthedChatRoute._addFileChildren(
  AuthedChatRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiAgentSessionsRouteChildren {
  ApiAgentSessionsIdRoute: typeof ApiAgentSessionsIdRoute
}

const ApiAgentSessionsRouteChildren: ApiAgentSessionsRouteChildren = {
  ApiAgentSessionsIdRoute: ApiAgentSessionsIdRoute,
}

const ApiAgentSessionsRouteWithChildren =
  ApiAgentSessionsRoute._addFileChildren(ApiAgentSessionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAgentAnswerRoute: ApiAgentAnswerRoute,
  ApiAgentCancelRoute: ApiAgentCancelRoute,
  ApiAgentContinueRoute: ApiAgentContinueRoute,
  ApiAgentKeysRoute: ApiAgentKeysRoute,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiAgentSessionReasoningRoute: ApiAgentSessionReasoningRoute,
  ApiAgentSessionsRoute: ApiAgentSessionsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiShapesSessionEventsRoute: ApiShapesSessionEventsRoute,
  ApiShapesSessionsRoute: ApiShapesSessionsRoute,
  ApiWebhookGithubRoute: ApiWebhookGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
